#!/usr/bin/env bash
# Generated by project-knowledge-bootstrap v1.1.2
# Version: 1.1.2
# Sync skill metadata to AGENTS.md Auto-invoke sections.
# Compatible with Bash 3+ (macOS default).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")"
SKILLS_DIR="$REPO_ROOT/skills"
DRY_RUN=false
FILTER_SCOPE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --scope) FILTER_SCOPE="$2"; shift 2 ;;
    --help|-h) echo "Usage: $0 [--dry-run] [--scope root]"; exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

get_agents_path() {
  scope="$1"
  case "$scope" in
    root) echo "$REPO_ROOT/AGENTS.md" ;;
    *) echo "" ;;
  esac
}

extract_field() {
  file="$1"
  field="$2"
  awk -v field="$field" '
    /^---$/ { fm = !fm; next }
    fm && $1 == field":" {
      sub(/^[^:]+:[[:space:]]*/, "")
      if ($0 != "" && $0 != ">") { gsub(/^"|"$/, ""); print; exit }
      getline
      while (/^[[:space:]]/ && !/^---$/) { sub(/^[[:space:]]+/, ""); printf "%s ", $0; if (!getline) break }
      print ""; exit
    }
  ' "$file" | sed 's/[[:space:]]*$//'
}

extract_metadata() {
  file="$1"
  field="$2"
  awk -v field="$field" '
    function trim(s) { sub(/^[[:space:]]+/, "", s); sub(/[[:space:]]+$/, "", s); return s }
    /^---$/ { fm = !fm; next }
    fm && /^metadata:/ { meta = 1; next }
    fm && meta && /^[a-z]/ && !/^[[:space:]]/ { meta = 0 }
    fm && meta && $1 == field":" {
      sub(/^[^:]+:[[:space:]]*/, "")
      if ($0 != "") { v=$0; gsub(/^"|"$/, "", v); gsub(/^\[|\]$/, "", v); print trim(v); exit }
      out=""
      while (getline) {
        if ($0 ~ /^---$/) break
        if ($0 ~ /^[a-z]/ && $0 !~ /^[[:space:]]/) break
        if ($0 ~ /^[[:space:]]*-[[:space:]]*/) {
          line=$0; sub(/^[[:space:]]*-[[:space:]]*/, "", line); line=trim(line); gsub(/^"|"$/, "", line)
          if (line != "") { if (out == "") out=line; else out=out "|" line }
        } else { break }
      }
      print out; exit
    }
  ' "$file"
}

[ -d "$SKILLS_DIR" ] || { echo "Skills directory not found: $SKILLS_DIR"; exit 1; }

TMPDIR_PATH=$(mktemp -d)
trap 'rm -rf "$TMPDIR_PATH"' EXIT

while IFS= read -r skill_file; do
  [ -f "$skill_file" ] || continue
  skill_name=$(extract_field "$skill_file" "name")
  scope_raw=$(extract_metadata "$skill_file" "scope")
  auto_raw=$(extract_metadata "$skill_file" "auto_invoke")
  [ -z "$skill_name" ] && continue
  [ -z "$scope_raw" ] && continue
  [ -z "$auto_raw" ] && continue

  echo "$scope_raw" | tr -d '[]' | tr ', ' '\n' | while read -r scope; do
    [ -z "$scope" ] && continue
    [ -n "$FILTER_SCOPE" ] && [ "$scope" != "$FILTER_SCOPE" ] && continue
    echo "$skill_name:$auto_raw" >> "$TMPDIR_PATH/$scope"
  done
done <<EOF
$(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name SKILL.md -print 2>/dev/null | sort)
EOF

updated=0
for scope_file in "$TMPDIR_PATH"/*; do
  [ -f "$scope_file" ] || continue
  scope=$(basename "$scope_file")
  agents_path=$(get_agents_path "$scope")
  [ -f "$agents_path" ] || continue

  rows_file=$(mktemp)
  while IFS= read -r entry; do
    skill_name="${entry%%:*}"
    actions="${entry#*:}"
    echo "$actions" | tr '|' '\n' | while read -r action; do
      action=$(echo "$action" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
      [ -z "$action" ] && continue
      printf "%s\t%s\n" "$action" "$skill_name" >> "$rows_file"
    done
  done < "$scope_file"

  section_file=$(mktemp)
  {
    echo "### Auto-invoke Skills"
    echo ""
    echo "When performing these actions, ALWAYS invoke the corresponding skill FIRST:"
    echo ""
    echo "| Action | Skill |"
    echo "| ------ | ----- |"
    LC_ALL=C sort -t "$(printf '\t')" -k1,1 -k2,2 "$rows_file" | while IFS="$(printf '\t')" read -r action skill_name; do
      [ -z "$action" ] && continue
      echo "| $action | \`$skill_name\` |"
    done
    echo ""
    echo "<!-- Generated by skills/skill-sync/assets/sync.sh — DO NOT edit manually -->"
  } > "$section_file"

  if $DRY_RUN; then
    echo "Would update $agents_path"
    cat "$section_file"
  else
    awk -v section_file="$section_file" '
      /^### Auto-invoke Skills/ {
        while ((getline line < section_file) > 0) print line
        close(section_file)
        skip=1
        next
      }
      skip && /^(---|## )/ { skip=0; print "" }
      !skip { print }
    ' "$agents_path" > "$agents_path.tmp"
    mv "$agents_path.tmp" "$agents_path"
    updated=$((updated + 1))
  fi
  rm -f "$rows_file" "$section_file"
done

echo "Skill sync complete: $updated AGENTS.md file(s) updated."
