#!/usr/bin/env bash
# Generated by project-knowledge-bootstrap v1.1.2
# Version: 1.1.2
# Setup AI Skills for Wrist Vehicle Bridge Frontend.
# Compatible with Bash 3+ (macOS default).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SKILLS_SOURCE="$SCRIPT_DIR"
USE_COPY=false

if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ -n "$MSYSTEM" ]]; then
  USE_COPY=true
fi

SETUP_CLAUDE=false
SETUP_CURSOR=false
SETUP_OPENCODE=false
SETUP_GEMINI=false
SETUP_COPILOT=false
SETUP_GLOBAL=false

show_help() {
  echo "Usage: $0 [--all] [--global] [--claude] [--cursor] [--opencode] [--gemini] [--copilot]"
}

install_skills() {
  target="$1"
  parent="$2"
  [ ! -d "$parent" ] && mkdir -p "$parent"

  if [ -L "$target" ]; then
    rm "$target"
  elif [ -d "$target" ]; then
    mv "$target" "$target.backup.$(date +%s)"
  fi

  if [ "$USE_COPY" = true ]; then
    cp -R "$SKILLS_SOURCE" "$target"
  else
    ln -s "$SKILLS_SOURCE" "$target"
  fi
}

copy_agents() {
  target_name="$1"
  if [ -f "$REPO_ROOT/AGENTS.md" ]; then
    cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/$target_name"
  fi
}

while [ $# -gt 0 ]; do
  case "$1" in
    --all) SETUP_CLAUDE=true; SETUP_CURSOR=true; SETUP_OPENCODE=true; SETUP_GEMINI=true; SETUP_COPILOT=true ;;
    --global) SETUP_GLOBAL=true ;;
    --claude) SETUP_CLAUDE=true ;;
    --cursor) SETUP_CURSOR=true ;;
    --opencode) SETUP_OPENCODE=true ;;
    --gemini) SETUP_GEMINI=true ;;
    --copilot) SETUP_COPILOT=true ;;
    --help|-h) show_help; exit 0 ;;
    *) echo "Unknown option: $1"; show_help; exit 1 ;;
  esac
  shift
done

if [ "$SETUP_CLAUDE$SETUP_CURSOR$SETUP_OPENCODE$SETUP_GEMINI$SETUP_COPILOT" = "falsefalsefalsefalsefalse" ]; then
  SETUP_OPENCODE=true
fi

if [ "$SETUP_GLOBAL" = true ]; then
  [ "$SETUP_CLAUDE" = true ] && install_skills "$HOME/.claude/skills" "$HOME/.claude" && cp "$REPO_ROOT/AGENTS.md" "$HOME/CLAUDE.md"
  [ "$SETUP_CURSOR" = true ] && install_skills "$HOME/.cursor/skills" "$HOME/.cursor" && cp "$REPO_ROOT/AGENTS.md" "$HOME/.cursorrules"
  [ "$SETUP_OPENCODE" = true ] && install_skills "$HOME/.config/opencode/skills" "$HOME/.config/opencode"
  [ "$SETUP_GEMINI" = true ] && install_skills "$HOME/.gemini/skills" "$HOME/.gemini" && cp "$REPO_ROOT/AGENTS.md" "$HOME/GEMINI.md"
else
  [ "$SETUP_CLAUDE" = true ] && install_skills "$REPO_ROOT/.claude/skills" "$REPO_ROOT/.claude" && copy_agents "CLAUDE.md"
  [ "$SETUP_CURSOR" = true ] && install_skills "$REPO_ROOT/.cursor/skills" "$REPO_ROOT/.cursor" && cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/.cursorrules"
  [ "$SETUP_OPENCODE" = true ] && install_skills "$REPO_ROOT/.opencode/skills" "$REPO_ROOT/.opencode"
  [ "$SETUP_GEMINI" = true ] && install_skills "$REPO_ROOT/.gemini/skills" "$REPO_ROOT/.gemini" && copy_agents "GEMINI.md"
  [ "$SETUP_COPILOT" = true ] && mkdir -p "$REPO_ROOT/.github" && cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/.github/copilot-instructions.md"
fi

echo "Skills setup complete."
