# Generated by project-knowledge-bootstrap v1.1.2
# Version: 1.1.2
# Setup AI Skills for Wrist Vehicle Bridge Frontend on Windows PowerShell.

param(
  [switch]$All,
  [switch]$Global,
  [switch]$Claude,
  [switch]$Cursor,
  [switch]$OpenCode,
  [switch]$Gemini,
  [switch]$Copilot,
  [switch]$Help
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$SkillsSource = $ScriptDir
$HomeDir = $env:USERPROFILE

function Show-Help {
  Write-Host "Usage: .\setup.ps1 [-All] [-Global] [-Claude] [-Cursor] [-OpenCode] [-Gemini] [-Copilot]"
}

function Copy-SkillsDirectory($Target, $Parent) {
  if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Path $Parent -Force | Out-Null }
  if (Test-Path $Target) {
    Move-Item -Path $Target -Destination "$Target.backup.$(Get-Date -Format 'yyyyMMddHHmmss')" -Force
  }
  Copy-Item -Path $SkillsSource -Destination $Target -Recurse -Force
}

if ($Help) { Show-Help; exit 0 }
if ($All) { $Claude = $true; $Cursor = $true; $OpenCode = $true; $Gemini = $true; $Copilot = $true }
if (-not ($Claude -or $Cursor -or $OpenCode -or $Gemini -or $Copilot)) { $OpenCode = $true }

$AgentsMd = Join-Path $RepoRoot "AGENTS.md"

if ($Global) {
  if ($Claude) { Copy-SkillsDirectory (Join-Path $HomeDir ".claude\skills") (Join-Path $HomeDir ".claude"); Copy-Item $AgentsMd (Join-Path $HomeDir "CLAUDE.md") -Force }
  if ($Cursor) { Copy-SkillsDirectory (Join-Path $HomeDir ".cursor\skills") (Join-Path $HomeDir ".cursor"); Copy-Item $AgentsMd (Join-Path $HomeDir ".cursorrules") -Force }
  if ($OpenCode) { Copy-SkillsDirectory (Join-Path $HomeDir ".opencode\skills") (Join-Path $HomeDir ".opencode") }
  if ($Gemini) { Copy-SkillsDirectory (Join-Path $HomeDir ".gemini\skills") (Join-Path $HomeDir ".gemini"); Copy-Item $AgentsMd (Join-Path $HomeDir "GEMINI.md") -Force }
} else {
  if ($Claude) { Copy-SkillsDirectory (Join-Path $RepoRoot ".claude\skills") (Join-Path $RepoRoot ".claude"); Copy-Item $AgentsMd (Join-Path $RepoRoot "CLAUDE.md") -Force }
  if ($Cursor) { Copy-SkillsDirectory (Join-Path $RepoRoot ".cursor\skills") (Join-Path $RepoRoot ".cursor"); Copy-Item $AgentsMd (Join-Path $RepoRoot ".cursorrules") -Force }
  if ($OpenCode) { Copy-SkillsDirectory (Join-Path $RepoRoot ".opencode\skills") (Join-Path $RepoRoot ".opencode") }
  if ($Gemini) { Copy-SkillsDirectory (Join-Path $RepoRoot ".gemini\skills") (Join-Path $RepoRoot ".gemini"); Copy-Item $AgentsMd (Join-Path $RepoRoot "GEMINI.md") -Force }
  if ($Copilot) { $GithubDir = Join-Path $RepoRoot ".github"; New-Item -ItemType Directory -Path $GithubDir -Force | Out-Null; Copy-Item $AgentsMd (Join-Path $GithubDir "copilot-instructions.md") -Force }
}

Write-Host "Skills setup complete."
